// <auto-generated />
using EsVideo.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EsVideo.Migrations
{
    [DbContext(typeof(ApllicatinDbContext))]
    partial class ApllicatinDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EsVideo.Model.Libro", b =>
                {
                    b.Property<string>("ISBN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Anno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Autore")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genere")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titolo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ISBN");

                    b.ToTable("SetLibri");

                    b.HasData(
                        new
                        {
                            ISBN = "9788804512763",
                            Anno = "1954",
                            Autore = "J.R.R. Tolkien",
                            Genere = "Fantasy",
                            Titolo = "Il signore degli anelli"
                        },
                        new
                        {
                            ISBN = "9788877827027",
                            Anno = "1997",
                            Autore = "J.K. Rowling",
                            Genere = "Fantasy",
                            Titolo = "Harry Potter e la Pietra Filosofale"
                        },
                        new
                        {
                            ISBN = "9780747543350",
                            Anno = "1998",
                            Autore = "J.K. Rowling",
                            Genere = "Fantasy",
                            Titolo = "Harry Potter e la Camera dei Segreti"
                        },
                        new
                        {
                            ISBN = "9780747546290",
                            Anno = "1999",
                            Autore = "J.K. Rowling",
                            Genere = "Fantasy",
                            Titolo = "Harry Potter e il Prigioniero di Azkaban"
                        },
                        new
                        {
                            ISBN = "9780747550990",
                            Anno = "2000",
                            Autore = "J.K. Rowling",
                            Genere = "Fantasy",
                            Titolo = "Harry Potter e il Calice di Fuoco"
                        },
                        new
                        {
                            ISBN = "9780747551002",
                            Anno = "2003",
                            Autore = "J.K. Rowling",
                            Genere = "Fantasy",
                            Titolo = "Harry Potter e l'Ordine della Fenice"
                        },
                        new
                        {
                            ISBN = "9780747591054",
                            Anno = "2005",
                            Autore = "J.K. Rowling",
                            Genere = "Fantasy",
                            Titolo = "Harry Potter e il Principe Mezzosangue"
                        },
                        new
                        {
                            ISBN = "9780747595861",
                            Anno = "2007",
                            Autore = "J.K. Rowling",
                            Genere = "Fantasy",
                            Titolo = "Harry Potter e i Doni della Morte"
                        },
                        new
                        {
                            ISBN = "9788804619169",
                            Anno = "1320",
                            Autore = "Dante Alighieri",
                            Genere = "Poesia epica",
                            Titolo = "Divina Commedia"
                        },
                        new
                        {
                            ISBN = "9788808222830",
                            Anno = "1949",
                            Autore = "George Orwell",
                            Genere = "Distopia",
                            Titolo = "1984"
                        },
                        new
                        {
                            ISBN = "9788882892547",
                            Anno = "1813",
                            Autore = "Jane Austen",
                            Genere = "Romanzo",
                            Titolo = "Orgoglio e Pregiudizio"
                        },
                        new
                        {
                            ISBN = "9788807821196",
                            Anno = "1847",
                            Autore = "Emily Bront�",
                            Genere = "Romanzo",
                            Titolo = "Cime tempestose"
                        },
                        new
                        {
                            ISBN = "9788845272814",
                            Anno = "1943",
                            Autore = "Antoine de Saint-Exup�ry",
                            Genere = "Romanzo",
                            Titolo = "Il Piccolo Principe"
                        },
                        new
                        {
                            ISBN = "9788845243227",
                            Anno = "1980",
                            Autore = "Umberto Eco",
                            Genere = "Romanzo giallo",
                            Titolo = "Il nome della rosa"
                        },
                        new
                        {
                            ISBN = "9788804490279",
                            Anno = "1937",
                            Autore = "J.R.R. Tolkien",
                            Genere = "Fantasy",
                            Titolo = "Lo Hobbit"
                        },
                        new
                        {
                            ISBN = "9788804543453",
                            Anno = "1950",
                            Autore = "C.S. Lewis",
                            Genere = "Fantasy",
                            Titolo = "Le cronache di Narnia"
                        },
                        new
                        {
                            ISBN = "9788817115373",
                            Anno = "1851",
                            Autore = "Herman Melville",
                            Genere = "Romanzo",
                            Titolo = "Moby Dick"
                        },
                        new
                        {
                            ISBN = "9788817179610",
                            Anno = "1605",
                            Autore = "Miguel de Cervantes",
                            Genere = "Romanzo",
                            Titolo = "Don Chisciotte"
                        },
                        new
                        {
                            ISBN = "9788804631154",
                            Anno = "1844",
                            Autore = "Alexandre Dumas",
                            Genere = "Romanzo",
                            Titolo = "Il conte di Montecristo"
                        },
                        new
                        {
                            ISBN = "9788804680497",
                            Anno = "1877",
                            Autore = "Lev Tolstoj",
                            Genere = "Romanzo",
                            Titolo = "Anna Karenina"
                        },
                        new
                        {
                            ISBN = "9788804623760",
                            Anno = "1869",
                            Autore = "Lev Tolstoj",
                            Genere = "Romanzo",
                            Titolo = "Guerra e Pace"
                        },
                        new
                        {
                            ISBN = "9788845241391",
                            Anno = "1951",
                            Autore = "J.D. Salinger",
                            Genere = "Romanzo",
                            Titolo = "Il giovane Holden"
                        },
                        new
                        {
                            ISBN = "9788804612658",
                            Anno = "1967",
                            Autore = "Gabriel Garc�a M�rquez",
                            Genere = "Romanzo",
                            Titolo = "Cent'anni di solitudine"
                        },
                        new
                        {
                            ISBN = "9788804618728",
                            Anno = "1952",
                            Autore = "Ernest Hemingway",
                            Genere = "Romanzo",
                            Titolo = "Il vecchio e il mare"
                        },
                        new
                        {
                            ISBN = "9788807900825",
                            Anno = "1925",
                            Autore = "F. Scott Fitzgerald",
                            Genere = "Romanzo",
                            Titolo = "Il grande Gatsby"
                        },
                        new
                        {
                            ISBN = "9788804395544",
                            Anno = "1866",
                            Autore = "F�dor Dostoevskij",
                            Genere = "Romanzo",
                            Titolo = "Delitto e castigo"
                        },
                        new
                        {
                            ISBN = "9788806140396",
                            Anno = "1890",
                            Autore = "Oscar Wilde",
                            Genere = "Romanzo",
                            Titolo = "Il ritratto di Dorian Gray"
                        },
                        new
                        {
                            ISBN = "9788817848474",
                            Anno = "1925",
                            Autore = "Franz Kafka",
                            Genere = "Romanzo",
                            Titolo = "Il processo"
                        },
                        new
                        {
                            ISBN = "9788804705854",
                            Anno = "1942",
                            Autore = "Albert Camus",
                            Genere = "Romanzo",
                            Titolo = "Lo straniero"
                        },
                        new
                        {
                            ISBN = "9788804616427",
                            Anno = "1967",
                            Autore = "Michail Bulgakov",
                            Genere = "Romanzo",
                            Titolo = "Il maestro e Margherita"
                        },
                        new
                        {
                            ISBN = "9788804677252",
                            Anno = "1926",
                            Autore = "Agatha Christie",
                            Genere = "Romanzo giallo",
                            Titolo = "L'assassinio di Roger Ackroyd"
                        },
                        new
                        {
                            ISBN = "9788804527101",
                            Anno = "1898",
                            Autore = "Henry James",
                            Genere = "Romanzo",
                            Titolo = "Il giro di vite"
                        },
                        new
                        {
                            ISBN = "9788804527102",
                            Anno = "1830",
                            Autore = "Stendhal",
                            Genere = "Romanzo",
                            Titolo = "Il rosso e il nero"
                        },
                        new
                        {
                            ISBN = "9788804613092",
                            Anno = "1857",
                            Autore = "Gustave Flaubert",
                            Genere = "Romanzo",
                            Titolo = "Madame Bovary"
                        },
                        new
                        {
                            ISBN = "9788804660803",
                            Anno = "1759",
                            Autore = "Laurence Sterne",
                            Genere = "Romanzo comico",
                            Titolo = "Vita e opinioni di Tristram Shandy, gentiluomo"
                        },
                        new
                        {
                            ISBN = "9788804516006",
                            Anno = "1876",
                            Autore = "Mark Twain",
                            Genere = "Romanzo",
                            Titolo = "Le avventure di Tom Sawyer"
                        },
                        new
                        {
                            ISBN = "9788804516013",
                            Anno = "1884",
                            Autore = "Mark Twain",
                            Genere = "Romanzo",
                            Titolo = "Le avventure di Huckleberry Finn"
                        },
                        new
                        {
                            ISBN = "9788899060687",
                            Anno = "1904",
                            Autore = "Emilio Salgari",
                            Genere = "Avventura",
                            Titolo = "La regina dei Caraibi"
                        },
                        new
                        {
                            ISBN = "9788804445678",
                            Anno = "1886",
                            Autore = "Robert Louis Stevenson",
                            Genere = "Romanzo",
                            Titolo = "Il dottor Jekyll e Mr. Hyde"
                        },
                        new
                        {
                            ISBN = "9788804504867",
                            Anno = "1972",
                            Autore = "Richard Adams",
                            Genere = "Romanzo",
                            Titolo = "La collina dei conigli"
                        },
                        new
                        {
                            ISBN = "9788804602089",
                            Anno = "1945",
                            Autore = "George Orwell",
                            Genere = "Romanzo",
                            Titolo = "La fattoria degli animali"
                        },
                        new
                        {
                            ISBN = "9788804602515",
                            Anno = "1874",
                            Autore = "Jules Verne",
                            Genere = "Avventura",
                            Titolo = "L'isola misteriosa"
                        },
                        new
                        {
                            ISBN = "9788804602508",
                            Anno = "1868",
                            Autore = "Jules Verne",
                            Genere = "Avventura",
                            Titolo = "I figli del capitano Grant"
                        },
                        new
                        {
                            ISBN = "9788804602492",
                            Anno = "1870",
                            Autore = "Jules Verne",
                            Genere = "Avventura",
                            Titolo = "Venti mila leghe sotto i mari"
                        },
                        new
                        {
                            ISBN = "9788842912222",
                            Anno = "1990",
                            Autore = "Terry Brooks",
                            Genere = "Fantasy",
                            Titolo = "Gli eredi di Shannara"
                        },
                        new
                        {
                            ISBN = "9788842904456",
                            Anno = "1977",
                            Autore = "Terry Brooks",
                            Genere = "Fantasy",
                            Titolo = "La spada di Shannara"
                        },
                        new
                        {
                            ISBN = "9788842914233",
                            Anno = "1992",
                            Autore = "Terry Brooks",
                            Genere = "Fantasy",
                            Titolo = "La regina degli elfi di Shannara"
                        },
                        new
                        {
                            ISBN = "9788842918187",
                            Anno = "1993",
                            Autore = "Terry Brooks",
                            Genere = "Fantasy",
                            Titolo = "I Talismani di Shannara"
                        },
                        new
                        {
                            ISBN = "9788842918194",
                            Anno = "1992",
                            Autore = "Terry Brooks",
                            Genere = "Fantasy",
                            Titolo = "La Canzone di Shannara"
                        },
                        new
                        {
                            ISBN = "9788804512770",
                            Anno = "1996",
                            Autore = "George R.R. Martin",
                            Genere = "Fantasy",
                            Titolo = "Il trono di spade"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
